name = "demo_tracking"
main = "src/index.ts"
compatibility_date = "2023-01-17"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "alandao-test"
database_id = "6e82d35c-9eac-4cb2-924c-5a01c4c5e6df"